packages:
  - packages/*

autoInstallPeers: false
allowBuilds:
  esbuild: true
minimumReleaseAgeExclude:
  - '@deepseek-ai/dsh-api-session-controller@0.2.0-rc.2'
  - '@deepseek-ai/dsh-brand@0.2.0-rc.2'
  - '@deepseek-ai/dsh-deque@0.2.0-rc.2'
  - '@deepseek-ai/dsh-workspace@0.2.0-rc.2'
